/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 database_l.glb -T 
Files: database_l.glb [1.17MB] > C:\Users\Fares\Documents\portfolio\public\models\database_l-transformed.glb [148.06KB] (87%)
Author: stefanorivera (https://sketchfab.com/stefanorivera)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/database-l-655f43f0712149798e441f015da87ba3
Title: Database L
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/database_l-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.a_silver_database_server_with_blue_lights_on_a_gray_background} />
    </group>
  )
}

useGLTF.preload('/database_l-transformed.glb')
