/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 neural_network.glb -T 
Files: neural_network.glb [1.5MB] > C:\Users\Fares\Documents\portfolio\public\models\neural_network-transformed.glb [98.33KB] (93%)
Author: Luisa (https://sketchfab.com/lvasquez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neural-network-4b44e03d032b42f58eaa5da6e2650a6a
Title: Neural Network
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/neural_network-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface48_lightGreen_0.geometry} material={materials.PaletteMaterial001} position={[-0.22, 1.029, 0.99]} rotation={[0.33, 0.177, -1.343]} scale={0.11} />
    </group>
  )
}

useGLTF.preload('/neural_network-transformed.glb')
